@startuml
title:根据钥匙获取卡号列表
autonumber
app->apps:/app/personal/key/list.do
note left:cardId 通行证编号\nuserId 通过token获取\nappId app应用号 通过头信息获取
apps->ams:入参卡号数组，请求日期，查询当前通行证对应的钥匙和锁信息
ams->ams:判断卡号状态
ams->ams:根据卡号，和状态，和请求日期 ，请求日期大于开始时间，小于结束时间查询钥匙信息表，得到钥匙信息list
ams->ams:循环钥匙信息list根据锁id查询终端信息表得到钥匙参数下发周期，和钥匙开锁类型，锁名称，锁mac地址，lKey,密码更新时长，秘钥更换时长，秘钥更换时长单位
ams->ams:判断记录的结束时间（end_dt）和请求日期+参数下发周期
alt 如果end_dt小于请求日期+参数下发周期
ams->ams:end_dt赋值给authEndDt
else 如果end_dt大于请求日期+参数下发周期
ams->ams:authEndDt即=请求日期+参数下发周期
end
ams->ams:根据钥匙id查询t_key_unlock_time表得到当前钥匙允许开锁时间段list
ams-->apps:返回卡list 及卡对应的(锁名称，钥匙有效期，钥匙授权有效期，锁mac地址，钥匙允许开锁时间段list，钥匙的开锁类型，钥匙参数下载标志,lkey，..)list

apps->apps: 对卡对应的list里面的每条数据进行签名
apps->apps: 循环list
alt 钥匙类型为密码类型
apps->apps:
else 钥匙类型为蓝牙类型
end

@enduml