=== 查询交易

- 流程

[plantuml, format="png", id="pbgea"]
----
!define send(a,b,c) a[#55ff55]->b: c
!define self(a, c) a[#ff2233]->a: c
!define resp(a,b,c) a<-[#green]-b: c

autonumber "<b>[00]"

title
查询交易
end title

send(Client, Server, 加密数据，平台代号如：cwv，csc)
self(Server,根据busi找到解密参数？？？)
self(Server,并查询交易)
resp(Client,Server,成功则返回地址)

----


[plantuml, format="png", id="pbgea"]
----
title
查询流程
end title

start

if (参数和Busi都不为空?) then (yes)
  :查询busi参数;
  :根据参数解密Data并读取解密数据到JSON;
  :读取交易的HASH（TxHash）;
  :OJpaDAO<CWVWltParameter>查询参数;
  if (参数OK) then (yes)
    :构造交易结构列表;
    while (下一个节点 available?)
      :查询当前TxHash;
      if (发现交易信息) then (yes)
        :匹配JSON;
        if (交易状态为空（status=null）) then (yes)
          :当前交易为空状态交易;
        else (no)
          :（E / D / 异常）状态交易汇集;
        endif
      else (no)
      endif
    endwhile
    :判断交易的合法性(2/3节点);
    if(D状态交易数量超2/3)then(yes)
        :组装数据并返回;
    elseif(E状态交易数量超2/3) then(yes)
        :组装数据并返回;
    elseif(none状态交易数量超2/3) then(yes)
        :组装数据并返回;
    else(异常)
        :返回异常（rpl_code = -2）;
    endif
  else (no)
    :交易查询URL异常;
  endif
else (no)
    :参数异常;
endif
stop

----

- 引用

@See http://172.18.80.253/blockchain/gameapi/blob/dev-refact/src/main/proto/wallet.proto[wallet.proto]
[NOTE]
====
- 请求：ReqGetTxByHash
- 返回：RespGetTxByHash
====


- 请求地址：
```
/wlt/pbqts.do
```
[source,http,options="nowrap"]
----
POST /wlt/pbqts.do HTTP/1.1
Content-Type: application/json
{
  "data":"加密的{\"hash\":\"交易的HASH\"}"
  "busi":"csc"
}
----

- 请求参数说明
|====
|Path|Type|Description|Essential

|`data`
|`String`
|加密{"hash":"交易的HASH"}
|必传

|`busi`
|`String`
|平台参数
|必传

|====

- 返回参数示例

----
{
  "rpl_code": 1,
  "rpl_msg": "message",
  "transaction": {
    "txHash": "",
    "txBody": {
      "inputs": [
        {
          "nonce": 1,
          "fee": 2,
          "feeLimit": 0,
          "address": "",
          "amount": "",
          "token": "",
          "symbol": "",
          "cryptoToken": ""
        },{
        }
      ],
      "outputs": [
        {
          "address": "",
          "amount": "",
          "symbol": "",
          "cryptoToken": ""
        },{
        }
      ],
      "exdata": "",
      "signatures": [
        {
          "signature": ""
        },
        {
          "signature": ""
        }
      ],
      "delegate": [
        "",
        "2"
      ],
      "data": "",
      "timestamp": 548761874943198,
      "type": 0,
      "cryptoTokenData":{
        "total:250
        "symbol:""
        "extData:[1,2,3,4]
        "name:["",""]
        "code:["",""]
      }
    },
    "node": {
      "node": "",
      "ip": "",
      "bcuid": ""
    },
    "status": "",
    "result": ""
  }
}
----

- 返回参数说明
|===
|Path|Type|Description

|`rpl_code`
|`int`
|响应码

|`rpl_msg`
|`int`
|响应信息

|`transaction`
|`Object`
|交易信息

|`transaction.txHash`
|`String`
|交易hash

|`transaction.txBody`
|`Object`
|交易内容体

|`transaction.txBody.inputs`
|`Array`
|发起方

|`transaction.txBody.inputs.nonce`
|`int`
|交易次数

|`transaction.txBody.inputs.fee`
|`int`
|手续费

|`transaction.txBody.inputs.feeLimit`
|`int`
|手续费限制

|`transaction.txBody.inputs.address`
|`String`
|发起方地址

|`transaction.txBody.inputs.amount`
|`String`
|交易金额

|`transaction.txBody.inputs.token`
|`String`
|ERC20 token名字

|`transaction.txBody.inputs.symbol`
|`String`
|ERC721 token标记

|`transaction.txBody.inputs.cryptoToken`
|`String`
|ERC721 token名字

|`transaction.txBody.outputs`
|`Array`
|接收方

|`transaction.txBody.outputs.address`
|`String`
|接收方地址

|`transaction.txBody.outputs.amount`
|`String`
|交易金额

|`transaction.txBody.outputs.symbol`
|`String`
|ERC721 token 标记

|`transaction.txBody.outputs.cryptoToken`
|`String`
|ERC721 token名字

|`transaction.txBody.exdata`
|`String`
|附属信息

|`transaction.txBody.signatures`
|`Array`
|签名信息

|`transaction.txBody.signatures.signature`
|`String`
|签名值

|`transaction.txBody.delegate`
|`Array`
|代理

|`transaction.txBody.data`
|`String`
|合约内容

|`transaction.txBody.timestamp`
|`int`
|时间戳

|`transaction.txBody.type`
|`int`
|交易类型

|`transaction.txBody.cryptoTokenData`
|`Object`
|ERC721 Token 信息

|`transaction.txBody.cryptoTokenData.total`
|`int`
|ERC721 Token 总量

|`transaction.txBody.cryptoTokenData.symbol`
|`String`
|ERC721 Token 名称

|`transaction.txBody.cryptoTokenData.extData`
|`byte Array`
|ERC721 Token 扩展信息

|`transaction.txBody.cryptoTokenData.name`
|`String Array`
|ERC721 Token 单个name

|`transaction.txBody.cryptoTokenData.code`
|`String Array`
|ERC721 Token 单个的ID


|`transaction.node`
|`Object`
|交易节点

|`transaction.node.node`
|`String`
|节点名称

|`transaction.node.ip`
|`String`
|节点IP

|`transaction.node.bcuid`
|`String`
|节点唯一标识

|`transaction.status`
|`String`
|交易状态

|`transaction.result`
|`String`
|合约返回结果

|===
