@startuml
title:锁的时间校准
autonumber
participant 智能锁
participant 小程序
participant 服务端
小程序->小程序:用户根据锁点击时间校准
小程序->小程序:取出蓝牙地址
小程序->小程序:校验蓝牙权限
alt 没有蓝牙权限
小程序->小程序:申请蓝牙权限，弹出提示框
小程序->小程序:用户点击拒绝授权蓝牙
小程序->小程序:提示无法连接锁
else 有蓝牙权限或者是打开了蓝牙权限
小程序->智能锁:根据mac地址连接锁
智能锁->智能锁:获取随机数进行签名
智能锁-->小程序:返回给小程序签名
小程序->服务端:根据签名到服务端产生时间校准指令
note left:锁的签名信息
服务端->服务端: 验指令
alt 验签失败
服务端-->小程序:返回连接锁错误
else 验签成功
服务端->服务端:根据服务器的ccksId对当前时间和锁的六位随机进行签名
服务端-->小程序:返回更新时间锁时间指令
小程序->智能锁:发送更新锁时间指令
智能锁->智能锁:校验签名，校验六位随机数是否存在
alt 随机数已过期
智能锁-->小程序:更新时间失败
else 随机数未过期
智能锁->智能锁:更新当前锁的时间
智能锁-->小程序:返回更新成功
end
end
end
@enduml