@startuml
autonumber
title:新查询收款人信息 lgm-apps
app->appmanage:查询收款客户信息
note left:手机号码/邮箱/userId type:1,2,3
appmanage->appmanage:判断用户是否存在
appmanage->appmanage:保存客户收款卡信息，付款卡信息到redis 产生token
appmanage->appmanage:判断是否发送短信
appmanage->app:token,客户信息
app->app:展示客户信息
@enduml