@startuml
autonumber
title:新查询收款人信息 lgm-apps
APP->APPS:查询收款客户信息
note left:手机号码/邮箱/userId type:1,2,3
APPS->APPS:判断用户是否存在
APPS->APPS:判断用户是否给自己转账
APPS->APPS:保存客户收款人需要展示的信息，付款卡信息到redis 产生token
APPS->APPS:如果收款人未存在默认卡，判断是否发送短信
APPS->APP:token,客户信息
APP->APP:展示客户信息
@enduml