@startuml
title:获取付款方式列表
autonumber
APP->APP:输入金额 点击转账
APP->APPS:查询付款方式列表
note left:转账金额（USD）\ntoken (查询收款人信息返回的token)
APPS->APPS:校验token的有效性
alt token超时
APPS-->APP:返回操作超时
else token 存在
APPS->APPS:重置token的有效时间
APPS->APPS:查询当前付款用户的的默认卡号信息
alt 默认卡号不存在
APPS->APPS:打印error 级别日志
APPS-->APP:返回卡号不存在
else 存在默认卡号
APPS->APPS:校验付款卡号和收款卡号的转账规则
alt 无转账规则
APPS->APPS:不返回余额方式
else 存在转账规则
APPS->APPS:查询付款卡余额信息
APPS->APPS:判断付款卡余额是否大于转账金额
alt 余额小于转账金额
APPS->APPS:设置余额付款方式为余额不足标识码
else 余额大于转账金额
APPS->APPS:查询付款方卡号的单笔限制最大最小金额
APPS->APPS:判断转账的金额是否在最大最小金额范围
alt 不在有效范围
APPS->APPS:标识余额付款方式不可用，返回给app最大转账金额数
else 在有效范围
APPS->APPS:标识余额付款方式可用
end
end
end
end
APPS->APPS:查询当前配置的渠道信息
alt 渠道信息为空
APPS-->APP:返回查询结果
else 渠道信息不为空
APPS->APPS:查询支付渠道为开的渠道
APPS->APPS:得到当前支付渠道限制的地区列表
APPS->APPS:判断当前渠道的地区列表是否支持用户的国家区号
alt 支持
APPS->APPS:判断转账的金额是否在渠道的最大最小金额范围
alt 在区间范围内
APPS->APPS:将渠道置为可用
else 不在区间范围内
APPS->APPS:将渠道置为不可用，并返回最大金额
end
end
end
APPS-->APP:返回支付方式列表
end
@enduml