@startuml
title:用户初始化
autonumber
APP->SDK:加载用户se
note left:外部用户号
SDK->TSM:申请用户se
note left:外部用户号 \nappId
TSM->UC:根据appId,外部用户号查询用户信息
UC->UC:查询appId类型，外部用户号是否存在
UC-->TSM:返回查询结果
TSM->TSM:判断查询结果
alt 是外部app且存在用户信息
TSM->ROUT:申请用户se
ROUT-->TSM:返回用户se
TSM-->SDK:返回用户se，cUserId
else 其他的出错
TSM-->SDK:返回用户信息异常
end
@enduml