= 区块浏览器
Lance;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 5
:sectlinks:
Doc Writer <fjy170@zcsmart.com>

[[overview]]
== 概要
   梳理节点管理器相关操作：
   . 梳理区块浏览器的各种查询流程

[NOTE]
- 交易：tx
- 块：block
- 账户：account
- 矿工：miner
- 附加数据：extData
- 平均：avg
- 时间：time
- 高度：number

[param-info]
== 参数信息

[param-info-query]
=== 获取额外的参数
- 描述

 用来获取额外的参数

- 引用

 @see [additional.proto] message ReqGetAdditional
 @see [additional.proto] message ResGetAdditional

- 请求地址： /pam/pbget.do
[source,http,options="nowrap"]
----
POST /pam/pbget.do HTTP/1.1
Content-Type: application/json
----

- 请求参数说明
 无

- 返回参数说明
|===
|Path|Type|Description

|`ret`
|`int`
|结果码

|`avgBlockTime`
|`String`
|平均出块时间

|`gtdps`
|`String`
|每秒产生交易数量

|`txCount`
|`int`
|所有区块中的交易总数

|`nodesCount`
|`String`
|所有节点数量

|`dConnectNodes`
|`String`
|已连接的节点数

|`pConnectNodes`
|`String`
|待连接的节点数

|`confirmTime`
|`String`
|最新5块中所有交易的平均确认时间

|===
- 返回参数示例
----
{
    "ret":"1",
    "avgBlockTime":"14",
    "gtdps":"1",
    "txCount":"20",
    "nodesCount":"15",
    "dConnectNodes":"1",
    "pConnectNodes":"12",
    "confirmTime":"5"

}
----
[node-list-query]
=== 获取所有节点列表
- 描述

 用来获取所有节点列表

- 引用

 @see [additional.proto] message ReqGetNodes
 @see [additional.proto] message ResGetNodes

- 请求地址： /pam/pbgns.do
[source,http,options="nowrap"]
----
POST /pam/pbgns.do HTTP/1.1
Content-Type: application/json
{
    "pageSize":10,
    "pageNo":1
}
----

- 请求参数说明
|===
|Path|Type|Description

|`pageSize`
|`int`
|每页显示条数 不传默认10条

|`pageNo`
|`int`
|查询第几页 默认第一页

|===
- 返回参数说明
|===
|Path|Type|Description

|`ret`
|`int`
|响应码

|`totalCount`
|`int`
|节点列表的总数

|`nodeInfos`
|`Array`
|节点信息

|`nodeInfos.nodeName`
|`String`
|节点名称

|`nodeInfos.uri`
|`String`
|节点ip

|`nodeInfos.startupTime`
|`int`
|启动时间

|`nodeInfos.publicKey`
|`String`
|该节点的公钥

|`nodeInfos.bcuid`
|`String`
|节点的唯一ID

|`nodeInfos.tryNodeIdIndex`
|`int`
|节点的随机id

|`nodeInfos.nodeIdIndex`
|`int`
|全网确定之后的节点id

|`nodeInfos.receiveCount`
|`int`
|总收到多少数据

|`nodeInfos.sendCount`
|`int`
|总发送多少数据

|`nodeInfos.blockCount`
|`int`
|总产生了多少个区块！

|`nodeInfos.status`
|`String`
|节点状态

|`nodeInfos.type`
|`String`
|节点类型

|===
- 返回参数示例
----
{
    "ret":1,
    "nodeInfos":[
        {
            "nodeName":"测试节点",
            "uri":"tcp，http/https",
            "startupTime":1452555,
            "publicKey":"2255",
            "bcuid":"dsfsdfsdf",
            "tryNodeIdIndex":22,
            "nodeIdIndex":20,
            "receiveCount":15,
            "sendCount":200,
            "blockCount":50,
            "status":"10",
            "type":"10"
        },...
}
----
[statistics-list]
=== 获取统计信息
- 描述

 用来根据统计类型获取各种数据的统计

- 引用

 @see [additional.proto] message ReqGetReportInfo
 @see [additional.proto] message ResGetReportInfo

- 请求地址： /pam/pbrep.do
[source,http,options="nowrap"]
----
POST /pam/pbrep.do HTTP/1.1
Content-Type: application/json
{
    "coin":"",
    "type":"",
    "splice":
}
----

- 请求参数说明
|===
|Path|Type|Description

|`coin`
|`String`
|需要查询的币的种类 暂时只使用我们中城自己的币

|`type`
|`String`
|统计类型 待补充 every_day_tx_count：每日交易笔数，every_day_tx_amount_count :查询每日交易额，every_day_blk_reward_count：查询每日区块奖励，every_day_active_count：查询每日活跃人数
|`splice`
|`int`
|查询多少天的统计

|===
- 返回参数说明
|===
|Path|Type|Description

|`ret`
|`int`
|响应码

|`reportResult`
|`Array`
|查询结果

|`dateTime`
|`String`
|时间信息

|`data`
|`String`
|时间对应的数据信息

|===
- 返回参数示例
----
{
    "ret":"1",
    "reportResult":[
        {
            "dateTime":"2018-01-02",
            "data":2555,
        },...
	]
}
----
[aggregate-list]
=== 聚合查询信息
- 描述

 用来在首页使用，可以根据多个条件进行查询

- 引用

 @see [additional.proto] message ReqGetAggInfo
 @see [additional.proto] message ResGetAggInfo

- 请求地址： /pam/pbagg.do
[source,http,options="nowrap"]
----
POST /pam/pbagg.do HTTP/1.1
Content-Type: application/json
{
    "keyword":""
}
----

- 请求参数说明
|===
|Path|Type|Description

|`keyword`
|`String`
|需要查询的关键字

|===
- 返回参数说明
|===
|Path|Type|Description

|`ret`
|`int`
|响应码

|`result`
|`String`
|用户查询的类型0:未查询到任何信息 1：普通账户地址，2：矿工的地址，3：交易的hash，4：区块的高度，5：区块的hash

|===
- 返回参数示例
----
{
    "ret":"1",
    "result":"1",
}
----
[address-info]
== 账户相关

[address-query]
=== 根据地址查询账户信息
- 描述

 用来根据地址查询账户信息

- 引用

 @see [address.proto] message ReqGetAddrDetailByAddr
 @see [address.proto] message ResGetAddrDetailByAddr

- 请求地址： /ads/pbgad.do
[source,http,options="nowrap"]
----
POST /ads/pbgad.do HTTP/1.1
Content-Type: application/json
{
    "address":"123456"
    "pageSize":10,
    "pageNo":1
}
----

- 请求参数说明
|===
|Path|Type|Description

|`address`
|`String`
|地址信息

|`pageSize`
|`String`
|当前账户的交易信息的每页显示条数 默认为10条

|`pageNo`
|`String`
|当前账户的交易信息的当前页

|===
- 返回参数说明
|===
|Path|Type|Description

|`ret`
|`int`
|响应码

|`totalCount`
|`int`
|总条数

|`addressInfo`
|`Object`
|账户信息

|`addressInfo.nonce`
|`String`
|交易次数

|`addressInfo.balance`
|`String`
|余额信息

|`addressInfo.address`
|`Array`
|地址信息

|`addressInfo.tokens`
|`Array`
|token信息

|`addressInfo.tokens.tokenName`
|`String`
|token名称

|`addressInfo.tokens.balance`
|`String`
|token余额

|`addressInfo.tokens.locked`
|`String`
|token是否被锁定

|`addressInfo.bcuid`
|`String`
|节点唯一id

|===
- 返回参数示例
----
{
    "ret":1,
    "totalCount":11,
    "addressInfo":{
        "bcuid":"",
        "nonce":"1",
        "balance":"100000",
        "address":["1","2"],
        "tokens":[
            {"tokenName":"1","balance":"1","locked":"1"},...
        ],
        "bcuid":"UUID"
    }
}
----
[address-query]
=== 根据地址查询账户交易信息
- 描述

 用来根据地址查询账户信息

- 引用

 @see [address.proto] message ReqGetAddrDetailByAddr
 @see [address.proto] message ResGetAddrDetailByAddr

- 请求地址： /ads/pbgtx.do
[source,http,options="nowrap"]
----
POST /ads/pbgtx.do HTTP/1.1
Content-Type: application/json
{
    "address":"123456",
    "pageSize":10,
    "pageNo":1
}
----

- 请求参数说明
|===
|Path|Type|Description

|`address`
|`String`
|地址信息

|`pageSize`
|`int`
|每页显示条数 默认10条

|`pageNo`
|`int`
|当前页 默认第一页

|===
- 返回参数说明
|===
|Path|Type|Description

|`ret`
|`int`
|响应码

|`addressInfo`
|`Object`
|账户信息

|`addressInfo.nonce`
|`String`
|交易次数

|`addressInfo.balance`
|`String`
|余额信息

|`addressInfo.address`
|`Array`
|地址信息

|`addressInfo.tokens`
|`Array`
|token信息

|`addressInfo.tokens.tokenName`
|`String`
|token名称

|`addressInfo.tokens.balance`
|`String`
|token余额

|`addressInfo.tokens.locked`
|`String`
|token是否被锁定

|`addressInfo.txs`
|`Array`
|交易信息

|`addressInfo.txs.status`
|`String`
|交易状态

|`addressInfo.txs.data`
|`String`
|数据

|`addressInfo.txs.txHash`
|`String`
|交易hash

|`addressInfo.txs.blockNumber`
|`int`
|块的高度

|`addressInfo.txs.timeStamp`
|`int`
|时间戳

|`addressInfo.txs.froms`
|`Array`
|发起者

|`addressInfo.txs.froms.nonce`
|`int`
|交易次数

|`addressInfo.txs.froms.address`
|`String`
|地址

|`addressInfo.txs.froms.amount`
|`String`
|数量

|`addressInfo.txs.froms.tokenName`
|`String`
|token

|`addressInfo.txs.froms.symbol`
|`String`
|币的简称

|`addressInfo.txs.tos`
|`Array`
|接收者信息

|`addressInfo.txs.tos.address`
|`String`
|接收者地址

|`addressInfo.txs.tos.amount`
|`String`
|数量

|`addressInfo.txs.tos.symbol`
|`String`
|币的简称

|`addressInfo.bcuid`
|`String`
|节点唯一id

|===
- 返回参数示例
----
{
    "ret":1,
    "addressInfo":{
        "bcuid":"",
        "nonce":"1",
        "balance":"100000",
        "address":["1","2"],
        "tokens":[
            {"tokenName":"1","balance":"1","locked":"1"},...
        ],
        "txs":[
            {
                "txHash":"2222",
                "blockNumber":2555,
                "timeStamp":1455555,
                "status":"1"
                "data":"",
                "froms":[
                    {
                        "nonce":1,
                        "address":"11111111",
                        "amount":"20",
                        "tokenName":"ERC-20",
                        "symbol":"eth"
                    },...
                ],
                "tos":[
                    {
                        "address":"dsfjsdkfhsdjkf",
                        "amount":"20",
                        "symbol":"eth"
                    },...
                ]
            },...
        ],
        "bcuid":"UUID"
    }
}
----
[block-info]
== 区块信息

[block-get-best]
=== 获取最新区块
- 描述

 用来获取最新区块

- 引用

 @see [block.proto] message ReqGetTheBestBlock
 @see [block.proto] message ResGetTheBestBlock

- 请求地址： /bok/pbgtb.do
[source,http,options="nowrap"]
----
POST /bok/pbgtb.do HTTP/1.1
Content-Type: application/json
----

- 请求参数说明
    无
- 返回参数说明
|===
|Path|Type|Description

|`ret`
|`int`
|响应码

|`block`
|`Object`
|块信息

|`block.header`
|`Object`
|块头信息

|`block.header.parentHash`
|`String`
|上一块的hash

|`block.header.txTrieRoot`
|`String`
|交易的root

|`block.header.timestamp`
|`int`
|时间戳

|`block.header.blockNumber`
|`int`
|块的高度

|`block.header.extData`
|`String`
|拓展信息

|`block.header.nonce`
|`String`
|交易次数

|`block.header.blockHash`
|`String`
|块的hash

|`block.header.txHashs`
|`Array`
|交易hash

|`block.header.txCount`
|`int`
|交易数

|`block.header.sliceId`
|`int`
|数据分片id

|`block.header.miner`
|`Object`
|矿工信息

|`block.header.miner.node`
|`String`
|出块节点

|`block.header.miner.reward`
|`String`
|出块奖励

|`block.header.miner.address`
|`String`
|地址

|`block.header.miner.bcuid`
|`String`
|出块的BCUID

|`block.header.nodes`
|`Array`
|节点信息

|`block.header.avetx`
|`String`
|块内平均交易时间

|===
- 返回参数示例
----
{
    "ret":"1",
    "block":{
       "header":{
            "parentHash":"1",
            "txTrieRoot":"1",
            "timestamp":1,
            "blockNumber":1,
            "extData":"1",
            "nonce":"1",
            "blockHash":"1",
            "txHashs":["1","2"],
            "txCount":1,
            "sliceId":1,
            "miner":{
                "node":"",
                "reward":"",
                "address":"",
                "bcuid":""
            },
            "nodes":"",
            "avetx":"2000"
       }
    }
}
----
[block-get-best]
=== 获取一组块
- 描述

 用来获取一组块

- 引用

 @see [block.proto] message ReqGetBatchBlocks
 @see [block.proto] message ResGetBatchBlocks

- 请求地址： /bok/pbgbb.do
[source,http,options="nowrap"]
----
POST /bok/pbgbb.do HTTP/1.1
Content-Type: application/json
{
    "pageNo":1,
    "pageSize":20
}
----

- 请求参数说明
|===
|Path|Type|Description

|`pageNo`
|`int`
|当前页

|`pageSize`
|`int`
|每页显示条数

|===
- 返回参数说明
|===
|Path|Type|Description

|`ret`
|`int`
|响应码

|`totalCount`
|`int`
|总条数

|`blocks`
|`Array`
|块信息

|`blocks.header`
|`Object`
|块头信息

|`blocks.header.parentHash`
|`String`
|上一块的hash

|`blocks.header.txTrieRoot`
|`String`
|交易的root

|`blocks.header.timestamp`
|`int`
|时间戳

|`blocks.header.blockNumber`
|`int`
|块的高度

|`block.header.extData`
|`String`
|拓展信息

|`blocks.header.nonce`
|`String`
|交易次数

|`blocks.header.blockHash`
|`String`
|块的hash

|`blocks.header.txHashs`
|`Array`
|交易hash

|`blocks.header.txCount`
|`int`
|交易数

|`blocks.header.sliceId`
|`int`
|数据分片id

|`blocks.header.miner`
|`Object`
|矿工信息

|`blocks.header.miner.node`
|`String`
|出块节点

|`blocks.header.miner.reward`
|`String`
|出块奖励

|`blocks.header.miner.address`
|`String`
|地址

|`blocks.header.miner.bcuid`
|`String`
|出块的BCUID

|`blocks.header.nodes`
|`Array`
|节点信息

|`blocks.header.avetx`
|`String`
|块内平均交易时间

|===
- 返回参数示例
----
{
    "ret":"1",
    "totalCount":1,
    "blocks":[
       {
            "header":{
                "parentHash":"1",
                "txTrieRoot":"1",
                "timestamp":1,
                "blockNumber":1,
                "extData":"1",
                "nonce":"1",
                "blockHash":"1",
                "txHashs":["1","2"],
                "txCount":1,
                "sliceId":1,
                "miner":{
                    "node":"",
                    "reward":"",
                    "address":"",
                    "bcuid":""
                },
                "nodes":"",
                "avetx":"2000"
            }
       },...
    ]
}
----
[block-get-detail]
=== 根据块hash获取块详情
- 描述

 用来根据块hash获取块详情

- 引用

 @see [block.proto] message ReqGetBlockByBlockHash
 @see [block.proto] message ResGetBlockByBlockHash

- 请求地址： /bok/pbgha.do
[source,http,options="nowrap"]
----
POST /bok/pbgha.do HTTP/1.1
Content-Type: application/json
{
    "blockHash":1
}
----

- 请求参数说明
|===
|Path|Type|Description

|`blockHash`
|`int`
|区块的hash

|===
- 返回参数说明
|===
|Path|Type|Description

|`ret`
|`int`
|响应码

|`block`
|`Object`
|块信息

|`block.header`
|`Object`
|块头信息

|`block.header.parentHash`
|`String`
|上一块的hash

|`block.header.txTrieRoot`
|`String`
|交易的root

|`block.header.timestamp`
|`int`
|时间戳

|`block.header.blockNumber`
|`int`
|块的高度

|`block.header.extData`
|`String`
|拓展信息

|`block.header.nonce`
|`String`
|交易次数

|`block.header.blockHash`
|`String`
|块的hash

|`block.header.txHashs`
|`Array`
|交易hash

|`block.header.txCount`
|`int`
|交易数

|`block.header.sliceId`
|`int`
|数据分片id

|`block.header.miner`
|`Object`
|矿工信息

|`block.header.miner.node`
|`String`
|出块节点

|`block.header.miner.reward`
|`String`
|出块奖励

|`block.header.miner.address`
|`String`
|地址

|`block.header.miner.bcuid`
|`String`
|出块的BCUID

|`block.header.nodes`
|`Array`
|节点信息

|`block.header.avetx`
|`String`
|块内平均交易时间

|===
- 返回参数示例
----
{
    "ret":"1",
    "totalCount":1,
    "block":{
       "header":{
            "parentHash":"1",
            "txTrieRoot":"1",
            "timestamp":1,
            "blockNumber":1,
            "extData":"1",
            "nonce":"1",
            "blockHash":"1",
            "txHashs":["1","2"],
            "txCount":1,
            "sliceId":1,
            "miner":{
                "node":"",
                "reward":"",
                "address":"",
                "bcuid":""
            },
            "nodes":"",
            "avetx":"2000"
       }
    }
}
----
[block-get-tx]
=== 根据块的高度获取块交易信息
- 描述

 用来根据块的高度获取块详情

- 引用

 @see [block.proto] message ReqGetTxByBlkHeight
 @see [block.proto] message ResGetTxByBlkHeight

- 请求地址： /bok/pbgbx.do
[source,http,options="nowrap"]
----
POST /bok/pbgbx.do HTTP/1.1
Content-Type: application/json
{
    "blockNumber":1,
    "pageSize":10,
    "pageNo":1
}
----

- 请求参数说明
|===
|Path|Type|Description

|`blockNumber`
|`int`
|块的高度

|`pageSize`
|`int`
|当前区块的交易信息进行分页 每页显示条数，默认每页10条

|`pageNo`
|`int`
|当前区块的交易信息进行分页,需要查询的页数，默认第一页

|===
- 返回参数说明
|===
|Path|Type|Description

|`ret`
|`int`
|响应码

|`txs`
|`Array`
|块交易信息

|`txs.status`
|`String`
|交易状态

|`txs.txHash`
|`String`
|交易hash

|`txs.blockNumber`
|`int`
|块的高度

|`txs.timeStamp`
|`int`
|时间戳

|`txs.froms`
|`Array`
|发起者

|`txs.froms.nonce`
|`int`
|交易次数

|`txs.froms.tokenName`
|`String`
|token的名称

|`txs.froms.address`
|`String`
|地址

|`txs.froms.amount`
|`String`
|数量

|`txs.tos`
|`Array`
|接收者信息

|`txs.tos.address`
|`String`
|接收者地址

|`txs.amount`
|`String`
|数量

|`totalCount`
|`int`
|总条数

|===
- 返回参数示例
----
{
    "ret":"1",
    "totalCount":1,
    "txs":[
       "txHash":"2222",
       "blockNumber":2555,
       "timeStamp":1455555,
       "status":"1"
       "data":"",
       "froms":[
           {
               "nonce":1,
               "address":"11111111",
               "amount":"20",
               "tokenName":""
           },...
       ],
       "tos":[
           {
               "address":"dsfjsdkfhsdjkf",
               "amount":"20",
           },...
       ]
    ]
}
----
[block-get-detail]
=== 根据块的高度获取块详情
- 描述

 用来根据块的高度获取块详情

- 引用

 @see [block.proto] message ReqGetBlockByBlockHeight
 @see [block.proto] message ResGetBlockByBlockHeight

- 请求地址： /bok/pbghe.do
[source,http,options="nowrap"]
----
POST /bok/pbghe.do HTTP/1.1
Content-Type: application/json
{
    "blockNumber":1,
    "pageSize":10,
    "pageNo":1
}
----

- 请求参数说明
|===
|Path|Type|Description

|`blockNumber`
|`int`
|块的高度

|`pageSize`
|`int`
|当前区块的交易信息进行分页 每页显示条数，默认每页10条

|`pageNo`
|`int`
|当前区块的交易信息进行分页,需要查询的页数，默认第一页

|===
- 返回参数说明
|===
|Path|Type|Description

|`ret`
|`int`
|响应码

|`block`
|`Object`
|块信息

|`block.header`
|`Object`
|块头信息

|`block.header.parentHash`
|`String`
|上一块的hash

|`block.header.txTrieRoot`
|`String`
|交易的root

|`block.header.timestamp`
|`int`
|时间戳

|`block.header.blockNumber`
|`int`
|块的高度

|`block.header.extData`
|`String`
|拓展信息

|`block.header.nonce`
|`String`
|交易次数

|`block.header.blockHash`
|`String`
|块的hash

|`block.header.txHashs`
|`Array`
|交易hash

|`block.header.txCount`
|`int`
|交易数

|`block.header.sliceId`
|`int`
|数据分片id

|`block.header.miner`
|`Object`
|矿工信息

|`block.header.miner.node`
|`String`
|出块节点

|`block.header.miner.reward`
|`String`
|出块奖励

|`block.header.miner.address`
|`String`
|地址

|`block.header.miner.bcuid`
|`String`
|出块的BCUID

|`block.header.nodes`
|`Array`
|节点信息

|`block.header.avetx`
|`String`
|块内平均交易时间

|===
- 返回参数示例
----
{
    "ret":"1",
    "totalCount":1,
    "block":{
       "header":{
            "parentHash":"1",
            "txTrieRoot":"1",
            "timestamp":1,
            "blockNumber":1,
            "extData":"1",
            "nonce":"1",
            "blockHash":"1",
            "txHashs":["1","2"],
            "txCount":1,
            "sliceId":1,
            "miner":{
                "node":"",
                "reward":"",
                "address":"",
                "bcuid":""
            },
            "nodes":"",
            "avetx":"2000"
       }
    }
}
----
[block-get-detail]
=== 根据交易hash获取块详情
- 描述

 用来根据交易hash获取块详情

- 引用

 @see [block.proto] message ReqGetBlockByTxHash
 @see [block.proto] message ResGetBlockByTxHash

- 请求地址： /bok/pbgth.do
[source,http,options="nowrap"]
----
POST /bok/pbgth.do HTTP/1.1
Content-Type: application/json
{
    "txHash":"2222"
}
----

- 请求参数说明
|===
|Path|Type|Description

|`txHash`
|`int`
|块的高度

|===
- 返回参数说明
|===
|Path|Type|Description

|`ret`
|`int`
|响应码

|`block`
|`Object`
|块信息

|`block.header`
|`Object`
|块头信息

|`block.header.parentHash`
|`String`
|上一块的hash

|`block.header.txTrieRoot`
|`String`
|交易的root

|`block.header.timestamp`
|`int`
|时间戳

|`block.header.blockNumber`
|`int`
|块的高度

|`block.header.extData`
|`String`
|拓展信息

|`block.header.nonce`
|`String`
|交易次数

|`block.header.blockHash`
|`String`
|块的hash

|`block.header.txHashs`
|`Array`
|交易hash

|`block.header.txCount`
|`int`
|交易数

|`block.header.sliceId`
|`int`
|数据分片id

|`block.header.miner`
|`Object`
|矿工信息

|`block.header.miner.node`
|`String`
|出块节点

|`block.header.miner.reward`
|`String`
|出块奖励

|`block.header.miner.address`
|`String`
|地址

|`block.header.miner.bcuid`
|`String`
|出块的BCUID

|`block.header.nodes`
|`Array`
|节点信息

|`block.header.avetx`
|`String`
|块内平均交易时间

|===
- 返回参数示例
----
{
    "ret":"1",
    "totalCount":1,
    "block":{
       "header":{
            "parentHash":"1",
            "txTrieRoot":"1",
            "timestamp":1,
            "blockNumber":1,
            "extData":"1",
            "nonce":"1",
            "blockHash":"1",
            "txHashs":["1","2"],
            "txCount":1,
            "sliceId":1,
            "miner":{
                "node":"",
                "reward":"",
                "address":"",
                "bcuid":""
            },
            "nodes":"",
            "avetx":"2000"
       }
    }
}
----
[block-get-detail]
=== 获取创始块
- 描述

 用来获取创始块

- 引用

 @see [block.proto] message ReqGetGenisBlock
 @see [block.proto] message RetGetGenisBlock

- 请求地址： /bok/pbggb.do
[source,http,options="nowrap"]
----
POST /bok/pbggb.do HTTP/1.1
Content-Type: application/json
----

- 请求参数说明
无
- 返回参数说明
|===
|Path|Type|Description

|`ret`
|`int`
|响应码

|`block`
|`Object`
|块信息

|`block.header`
|`Object`
|块头信息

|`block.header.parentHash`
|`String`
|上一块的hash

|`block.header.txTrieRoot`
|`String`
|交易的root

|`block.header.timestamp`
|`int`
|时间戳

|`block.header.blockNumber`
|`int`
|块的高度

|`block.header.extData`
|`String`
|拓展信息

|`block.header.nonce`
|`String`
|交易次数

|`block.header.blockHash`
|`String`
|块的hash

|`block.header.txHashs`
|`Array`
|交易hash

|`block.header.txCount`
|`int`
|交易数

|`block.header.sliceId`
|`int`
|数据分片id

|`block.header.miner`
|`Object`
|矿工信息

|`block.header.miner.node`
|`String`
|出块节点

|`block.header.miner.reward`
|`String`
|出块奖励

|`block.header.miner.address`
|`String`
|地址

|`block.header.miner.bcuid`
|`String`
|出块的BCUID

|`block.header.nodes`
|`Array`
|节点信息

|`block.header.avetx`
|`String`
|块内平均交易时间

|===
- 返回参数示例
----
{
    "ret":"1",
    "totalCount":1,
    "block":{
       "header":{
            "parentHash":"1",
            "txTrieRoot":"1",
            "timestamp":1,
            "blockNumber":1,
            "extData":"1",
            "nonce":"1",
            "blockHash":"1",
            "txHashs":["1","2"],
            "txCount":1,
            "sliceId":1,
            "miner":{
                "node":"",
                "reward":"",
                "address":"",
                "bcuid":""
            },
            "nodes":"",
            "avetx":"2000"
       }
    }
}
----

[tx]
== 交易

[block-get-detail]
=== 获取所有区块的hash (废弃)
- 描述

 用来获取所有区块的hash

- 引用

 @see [tx.proto] message ReqGetTxByTxHash
 @see [tx.proto] message ResGetTxByTxHash

- 请求地址： /trx/pbgbs.do
[source,http,options="nowrap"]
----
POST /trx/pbgbs.do HTTP/1.1
Content-Type: application/json
{
    "number":1
}
----

- 请求参数说明
|===
|Path|Type|Description

|`number`
|`int`
|块高度

|===
- 返回参数说明
|===
|Path|Type|Description

|`blocks`
|`Array`
|块信息

|`blocks.blockHash`
|`String`
|块的hash

|`blocks.parentHash`
|`String`
|上一个块的hash

|`blocks.blockNumber`
|`int`
|块里面的交易数量

|`blocks.state`
|`String`
|状态树根节点的Hash值

|`blocks.receipt`
|`String`
|交易结果的根的hash值

|`blocks.txTrieRoot`
|`String`
|交易数据的根hash值

|`blocks.timestamp`
|`int`
|时间戳

|`blocks.miner`
|`String`
|旷工的地址

|===
- 返回参数示例
----
{
    "ret":"1",
    "blocks":[
        {
            "blockHash":"",
            "parentHash":"",
            "blockNumber":1,
            "state":"",
            "receipt":"",
            "txTrieRoot":"2345",
            "timestamp":145254256,
            "miner":111
        }
    ]
}
----

[block-get-detail]
=== 根据交易hash获取交易详情
- 描述

 用来根据交易hash获取交易详情

- 引用

 @see [tx.proto] message ReqGetTxByTxHash
 @see [tx.proto] message ResGetTxByTxHash

- 请求地址： /txs/pbgtt.do
[source,http,options="nowrap"]
----
POST /txs/pbgtt.do HTTP/1.1
Content-Type: application/json
{
    "txHash":"1231232"
}
----

- 请求参数说明
|===
|Path|Type|Description

|`txHash`
|`String`
|交易的hash

|===
- 返回参数说明
|===
|Path|Type|Description

|`ret`
|`int`
|响应码
|`txs`
|`Array`
|交易信息

|`txs.status`
|`String`
|交易状态

|`txs.data`
|`String`
|数据

|`txs.txHash`
|`String`
|交易hash

|`txs.blockNumber`
|`int`
|块的高度

|`txs.timeStamp`
|`int`
|时间戳

|`txs.froms`
|`Array`
|发起者

|`txs.froms.nonce`
|`int`
|交易次数

|`txs.froms.address`
|`String`
|地址

|`txs.froms.amount`
|`String`
|数量

|`txs.froms.pubKey`
|`String`
|公钥

|`txs.froms.tokenName`
|`String`
|token

|`txs.froms.symbol`
|`String`
|币的简称

|`txs.tos`
|`Array`
|接收者信息

|`txs.tos.address`
|`String`
|接收者地址

|`txs.tos.amount`
|`String`
|数量

|`txs.tos.symbol`
|`String`
|币的简称

|===
- 返回参数示例
----
{
    "ret":"1",
    "txs":
        {
            "txHash":"2222",
            "blockNumber":2555,
            "timeStamp":1455555,
            "status":"1"
            "data":"",
            "froms":[
                {
                    "nonce":1,
                    "fee":20,
                    "feeLimit":10,
                    "address":"11111111",
                    "amount":"20",
                    "pubKey":"111111",
                    "tokenName":"ERC-20",
                    "symbol":"eth"
                },...
            ],
            "tos":[
                {
                    "address":"dsfjsdkfhsdjkf",
                    "amount":"20",
                    "symbol":"eth"
                },...
            ]
         }
}
----
[block-get-detail]
=== 根据账户地址获取交易详情
- 描述

 用来根据账户地址获取交易详情

- 引用

 @see [tx.proto] message ReqGetTxByAddress
 @see [tx.proto] message ResGetTxByAddress

- 请求地址： /txs/pbgta.do
[source,http,options="nowrap"]
----
POST /txs/pbgta.do HTTP/1.1
Content-Type: application/json
{
    "address":"1231232",
    "pageSize":10,
    "pageNo":1,
}
----

- 请求参数说明
|===
|Path|Type|Description

|`address`
|`String`
|账户的地址

|`pageSize`
|`int`
|每页显示条数 默认是10条

|`pageNo`
|`int`
|查询的页数，默认是1页


|===
- 返回参数说明
|===
|Path|Type|Description

|`ret`
|`int`
|响应码
|`txs`
|`Array`
|交易信息

|`txs.status`
|`String`
|交易状态

|`txs.data`
|`String`
|数据

|`txs.txHash`
|`String`
|交易hash

|`txs.blockNumber`
|`int`
|块的高度

|`txs.timeStamp`
|`int`
|时间戳

|`txs.froms`
|`Array`
|发起者

|`txs.froms.nonce`
|`int`
|交易次数

|`txs.froms.address`
|`String`
|地址

|`txs.froms.amount`
|`String`
|数量

|`txs.froms.pubKey`
|`String`
|公钥

|`txs.froms.tokenName`
|`String`
|token

|`txs.froms.symbol`
|`String`
|币的简称

|`txs.tos`
|`Array`
|接收者信息

|`txs.tos.address`
|`String`
|接收者地址

|`txs.tos.amount`
|`String`
|数量

|`txs.tos.symbol`
|`String`
|币的简称

|===
- 返回参数示例
----
{
    "ret":"1",
    "txs":[
        {
            "txHash":"2222",
            "blockNumber":2555,
            "timeStamp":1455555,
            "status":"1"
            "data":"",
            "froms":[
                {
                    "nonce":1,
                    "address":"11111111",
                    "amount":"20",
                    "pubKey":"111111",
                    "tokenName":"ERC-20",
                    "symbol":"eth"
                },...
            ],
            "tos":[
                {
                    "address":"dsfjsdkfhsdjkf",
                    "amount":"20",
                    "symbol":"eth"
                },...
            ]
        },...
	]
}
----

[tx-get-list]
=== 获取交易列表
- 描述

 用来使用分页获取交易列表

- 引用

 @see [tx.proto] message ReqGetTxList
 @see [tx.proto] message ResGetTxList

- 请求地址： /txs/pbtxl.do
[source,http,options="nowrap"]
----
POST /txs/pbtxs.do HTTP/1.1
Content-Type: application/json
{
    "pageSize":10,
    "pageNo":0
}
----

- 请求参数说明
|===
|Path|Type|Description

|`pageSize`
|`int`
|每页显示条数 默认10条

|`pageNo`
|`int`
|当前页 默认0

|===
- 返回参数说明
|===
|Path|Type|Description

|`ret`
|`int`
|响应码

|`txs`
|`Array`
|交易信息

|`txs.status`
|`String`
|交易状态

|`txs.txHash`
|`String`
|交易hash

|`txs.blockNumber`
|`int`
|块的高度

|`txs.timeStamp`
|`int`
|时间戳

|`totalCount`
|`int`
|总条数

|===
- 返回参数示例
----
{
    "ret":"1",
    "totalCount":1
    "txs":[
        {
            "txHash":"2222",
            "blockNumber":2555,
            "timeStamp":1455555,
            "status":"1"
        },...
	]
}
----